/*
	Mod Support RwF Localisation
	Credits: SeelingCat
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT OR REPLACE INTO LocalizedText
		(Tag,																			Language,	Text						)
VALUES	("LOC_CIVILIZATION_CVS_MALAYSIA_DESCRIPTION_JFD_CIVILIZATION",					"en_US",	"Malay Empire"				),

		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_MALAYSIA",						"en_US",	"Ketua"						),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_MALAYSIA_FEMININE",				"en_US",	"Ketua"						),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_MALAYSIA",							"en_US",	"Komander"					),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_MALAYSIA_FEMININE",					"en_US",	"Komander"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_MALAYSIA",							"en_US",	"Master"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_MALAYSIA_FEMININE",					"en_US",	"Master"					),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_MALAYSIA",						"en_US",	"Putera"					),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",				"en_US",	"Puteri"					),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_MALAYSIA",						"en_US",	"Bendahara"					),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",				"en_US",	"Bendahari"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA",			"en_US",	"Bendahara"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",	"en_US",	"Bendahari"					),

		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_MALAYSIA",				"en_US",	"Putera"					),
		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",		"en_US",	"Puteri"					),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA",				"en_US",	"Bendahara"					),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA_FEMININE",		"en_US",	"Bendahari"					),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_MALAYSIA",			"en_US",	"Imam"						),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",	"en_US",	"Pendeta"					),

		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_MALAYSIA",						"en_US",	"Sultan"					),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",				"en_US",	"Sultan"					),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA",					"en_US",	"Putera"					),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA_FEMININE",		"en_US",	"Puteri"					),
		
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA",				"en_US",	"Bendahara"					),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_MALAYSIA_FEMININE",		"en_US",	"Bendahari"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA",				"en_US",	"Menteri"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_MALAYSIA_FEMININE",		"en_US",	"Menteri"					),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_MALAYSIA",			"en_US",	"Tuan"						),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_MALAYSIA_FEMININE",	"en_US",	"Tuani"						),
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_MALAYSIA",							"en_US",	"Sultan"					),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_MALAYSIA_FEMININE",				"en_US",	"Sultan"					);

